id: uv_light_schedule
alias: Follow Seed Starter Light Schedule
trigger:
  - platform: state
    entity_id: binary_sensor.seed_starter_light_schedule
action:
  - alias: "Select service to call"
    choose:
    - conditions: |
        {{ trigger.to_state.state == 'on' }}
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.seed_starter_uv_light
    - conditions: |
        {{ trigger.to_state.state == 'off' }}
      sequence:
        - service: light.turn_off
          target:
            entity_id: light.seed_starter_uv_light