id: fire_dying
alias: "Notify me if the wood furnace gets below certain temperatures"
trigger:
  - platform: numeric_state
    entity_id: 
      - sensor.wood_furnace_temperature
    below: 100
  - platform: numeric_state
    entity_id: 
      - sensor.wood_furnace_temperature
    below: 90
  - platform: numeric_state
    entity_id: 
      - sensor.wood_furnace_temperature
    below: 85
  - platform: numeric_state
    entity_id: 
      - sensor.wood_furnace_temperature
    below: 82
  - platform: numeric_state
    entity_id: 
      - sensor.wood_furnace_temperature
    below: 79
  - platform: numeric_state
    entity_id: 
      - sensor.wood_furnace_temperature
    below: 75

action:
  - choose:
      - alias: "Alert that the fire is dying"
        conditions:
          - "{{ trigger.to_state <= 82 }}"
        sequence:
          - service: notify.household_ios
            data:
              title: Wood Furnace
              message: "I'm not so sure there's a fire anymore. It's at {{trigger.to_state.state}}ยบ. Feed me!"
              data:
                  push:
                    interruption-level: time-sensitive
      - alias: "Warn that the fire might be dying"
        conditions:
          - "{{ trigger.to_state < 90 }}"
        sequence:
          - service: notify.household_ios
            data:
              title: Wood Furnace
              message: "The fire is starting to die down. It's at {{trigger.to_state.state}}ยบ."
              data:
                  push:
                    interruption-level: time-sensitive
    default:
      - service: notify.household_ios
        data:
          title: Wood Furnace
          message: "The fire is getting cooler. It's at {{trigger.to_state.state}}ยบ."
          data:
              push:
                interruption-level: time-sensitive