# The throughput of the device pluged into the Ethernet WAN port of the Cradlepoint router (in this
# case, happens to be Starlink)

resource: http://192.168.10.1/api/status/wan/devices/ethernet-wan/stats
username: !secret network_cradlepoint_username
password: !secret network_cradlepoint_password
authentication: basic
sensor:
  - name: Starlink download total bytes
    state_class: total_increasing
    unit_of_measurement: B
    value_template: |-
      {{ value_json.data["in"] }}
    unique_id: cradlepoint_wan_download_bytes

  - name: Starlink upload total bytes
    state_class: total_increasing
    unit_of_measurement: B
    value_template: |-
      {{ value_json.data.out }}
    unique_id: cradlepoint_wan_upload_bytes