input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
automation: !include notifications.yaml
template: !include_dir_list templates/
sensor:
  - !include furnace_usage_since_last_check.yaml