# Configuration for the HTTP Service
http: !include http.yaml

# Enable Wake-on-LAN
wake_on_lan:

# Load various entity configurations
switch: !include_dir_list switch

# RESTful sensors
# https://www.home-assistant.io/integrations/rest
rest: !include_dir_list rest
