# Configuration for the HTTP Service
http: !include http.yaml

# Enable Wake-on-LAN
wake_on_lan:

# Load various entity configurations
switch: !include_dir_list switch

# RESTful sensors
# https://www.home-assistant.io/integrations/rest
rest: !include_dir_list rest

# Template sensors
# https://www.home-assistant.io/integrations/template/
template:
  - sensor: !include_dir_list template/sensor

# Utility meters
utility_meter: !include_dir_named utility_meter

automation: !include_dir_list automations