# Configuration for the HTTP Service
http: !include http.yaml

# Enable Wake-on-LAN
wake_on_lan:

# Load various entity configurations
switch: !include_dir_list switch
sensor: !include_dir_list sensor
