# Gets the estimated gas tank from furnace runtime since last measurement
sensor:
  - name: Estimated gas tank level
    unit_of_measurement: "%"
    state: |
      {{  
        states.input_number.last_measured_gas_tank_level.state - (
          100
            * states.input_number.tank_usage_factor.state
            * states.sensor.furnace_usage_since_last_check.state
        )
      }} | 
    unique_id: climate.gas_tracking.estimated_gas_tank_level