## Generic start for Sonoff S31 devices

esphome:
  name: $device_name

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_sk

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

api:

ota:

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    id: button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "$friendly_name Status"
  - platform: template
    name: "$friendly_name Breaker Tripped"
    id: breaker
    device_class: problem
    on_press:
      then:
        - switch.turn_off: relay
        - light.turn_on: 
            id: led
            effect: Breaker Tripped
    on_release:
      then:
        - light.turn_off: led


sensor:
  - platform: wifi_signal
    name: "$friendly_name Wifi Signal"
    update_interval: 15s
  - platform: cse7766
    current:
      name: "$friendly_name Current"
      accuracy_decimals: 1
    voltage:
      name: "$friendly_name Voltage"
      accuracy_decimals: 1
    power:
      name: "$friendly_name Power"
      accuracy_decimals: 1
      id: power
      on_value_range:
        above: $watt_limit
        then: 
          - binary_sensor.template.publish: 
              id: breaker
              state: ON
    update_interval: 5s
  - platform: integration
    name: "$friendly_name Energy"
    sensor: power
    time_unit: h
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001

time:
  - platform: sntp
    id: the_time

switch:
  - platform: gpio
    name: "$friendly_name Power"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        - binary_sensor.template.publish:
            id: breaker
            state: OFF

light:
  - platform: status_led
    pin: 
      number: GPIO13
      inverted: True
    id: led
    internal: True
    effects:
      - lambda: 
          name: "Breaker Tripped"
          update_interval: 250ms
          lambda: |-
            static int state = 0;
            auto call = id(led).turn_on();
            call.set_brightness(state == 1);
            call.perform();
            state = (state + 1) % 2;
    restore_mode: ALWAYS_OFF