## Generic start for Sonoff basic R2 devices
esphome:
  name: $device_name

esp8266:
  board: esp8285

wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_sk

logger:
api:
ota:

# Device specific config

binary_sensor:
  - platform: gpio
    id: push_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    internal: true
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "$friendly_name Status"

switch:
  # The relay switches on the red side of the LED when active.
  - platform: gpio
    name: "$friendly_name Power"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

light:
  - platform: status_led
    pin:
      number: GPIO13
      inverted: True
    id: blue_led
    internal: True
    restore_mode: ALWAYS_OFF
    effects:
      - lambda:
          name: "Identify"
          update_interval: 500ms
          lambda: |-
            static int state = 0;
            auto call = id(blue_led).turn_on();
            call.set_brightness(state == 0);
            call.perform();
            state = (state + 1) % 2;