influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb_host
  port: 8086
  token: !secret influxdb_token
  organization: !secret influxdb_organizaiton
  bucket: homeassistant
  tags:
    source: HA
  tags_attributes:
    - friendly_name

#influx_logger:
#  url: !secret influxdb_url
#  token: !secret influxdb_token
#  organization: !secret influxdb_organization
#  bucket: homeassistant
