<<: !include hardware/nodemcu.yaml

esphome:
  name: christmas-tree
  includes: christmas_tree.h
  on_boot:
    priority: 600
    then: 
      - button.press: reset_lights

# An output that does nothing
# Used for effect lights that store a color, but don't actually go anywhere
output:
  - platform: template
    id: output_blackhole
    type: float
    write_action: []

# Re-usable configs
.defs:
  # A light with no output - used to define colors for effects
  effect_light: &effect_light
    platform: rgb
    red: output_blackhole
    green: output_blackhole
    blue: output_blackhole
    gamma_correct: 1
    entity_category: config
    icon: "mdi:palette"

light:
  - name: "Christmas Tree LEDs"
    id: main_light
    platform: neopixelbus
    type: RGB
    pin: GPIO3
    variant: WS2811
    num_leds: 150
    gamma_correct: 1
    icon: "mdi:string-lights"
    effects:
      - addressable_lambda:
          name: "Solid 4-Color"
          update_interval: 0ms
          lambda: |-
            do_solid_color_effect(it);
      - addressable_lambda:
          name: "Marquee 4-Color"
          update_interval: 0ms
          lambda: |-
            do_marquee_effect(it);
      - addressable_lambda:
          name: Solid Fade 4-Color
          update_interval: 0ms
          lambda: |-
            do_solid_fade_effect(it);
      - addressable_rainbow:
          name: Rainbow Tree 🌈
          speed: 25
          width: 100
      - addressable_twinkle:
          name: Twinkly Lights
          twinkle_probability: 20%
      - addressable_random_twinkle:
          name: Colorful Twinkly Lights
          twinkle_probability: 20%
      - addressable_lambda:
          name: 4-Color Cycle
          update_interval: 0ms
          lambda: |-
            do_cycle_effect(it);
      - addressable_lambda:
          name: 3-Color Cycle
          update_interval: 0ms
          lambda: |-
            do_cycle_effect(it, 3);
      - addressable_lambda:
          name: 2-Color Cycle
          update_interval: 0ms
          lambda: |-
            do_cycle_effect(it, 2);


  # Fake lights - used in effects
  - name: "Christmas Tree Effect Color 1"
    id: effect_color_1
    <<: *effect_light
  - name: "Christmas Tree Effect Color 2"
    id: effect_color_2
    <<: *effect_light
  - name: "Christmas Tree Effect Color 3"
    id: effect_color_3
    <<: *effect_light
  - name: "Christmas Tree Effect Color 4"
    id: effect_color_4
    <<: *effect_light

button:
  - name: "Reset Christmas Tree Effect Colors"
    platform: template
    id: reset_lights
    on_press:
      - light.turn_on:
          id: effect_color_1
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%
      - light.turn_on:
          id: effect_color_2
          red: 0%
          green: 100%
          blue: 0%
          brightness: 100%
      - light.turn_on:
          id: effect_color_3
          red: 0%
          green: 0%
          blue: 100%
          brightness: 100%
      - light.turn_on:
          id: effect_color_4
          red: 100%
          green: 50%
          blue: 0%
          brightness: 100%
      - light.turn_on:
          id: main_light
          red: 100%
          green: 62%
          blue: 19%
          brightness: 100%
