substitutions:
  node_name: christmas-tree

<<: !include hardware/nodemcu.yaml

# An output that does nothing
# Used for effect lights that store a color, but don't actually go anywhere
output:
  - platform: template
    id: output_blackhole
    type: float
    write_action: []

# Re-usable configs
.defs:
  # A light with no output - used to define colors for effects
  effect_light: &effect_light
    platform: rgb
    red: output_blackhole
    green: output_blackhole
    blue: output_blackhole
    gamma_correct: 1
    entity_category: config
    icon: "mdi:palette"

light:
  - name: "Christmas Tree LEDs"
    platform: neopixelbus
    type: RGB
    pin: GPIO3
    variant: WS2811
    num_leds: 150
    gamma_correct: 1
    effects:
      addressable_lambda:
        name: "Solid 4-Color"
        update_interval: 0ms
        lambda: |-
          esphome::light::LightState* c;
          float r, g, b;
          for (int i = it.size() - 1; i > 0; i--) {
              if (i % 4 == 0) {
                c = id(effect_color_1);
              } else if (i % 4 == 1) {
                c = id(effect_color_2);
              } else if (i % 4 == 2) {
                c = id(effect_color_3);
              } else {
                c = id(effect_color_4);
              }
              c->current_values_as_rgb(&r, &g, &b);
              it[i] = Color(r * 255, g * 255, b * 255);
          }

  # Fake lights - used in effects
  - name: "Christmas Tree Effect Color 1"
    id: effect_color_1
    <<: *effect_light
  - name: "Christmas Tree Effect Color 2"
    id: effect_color_2
    <<: *effect_light
  - name: "Christmas Tree Effect Color 3"
    id: effect_color_3
    <<: *effect_light
  - name: "Christmas Tree Effect Color 4"
    id: effect_color_4
    <<: *effect_light

button:
  - name: "Reset Christmas Tree Effect Colors"
    platform: template
    on_press:
      - light.turn_on:
          id: effect_color_1
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%
      - light.turn_on:
          id: effect_color_2
          red: 0%
          green: 0%
          blue: 0%
          brightness: 100%
      - light.turn_on:
          id: effect_color_3
          red: 0%
          green: 0%
          blue: 100%
          brightness: 100%
      - light.turn_on:
          id: effect_color_4
          red: 100%
          green: 25%
          blue: 0%
          brightness: 100%
