substitutions:
  node_name: christmas-tree

<<: !include hardware/nodemcu.yaml

output:
  - platform: template
    id: output_blackhole
    type: float
    write_action: []

.defs:
  # A light with no output - used to define colors for effects
  effect_light: &effect_light
    platform: rgb
    red: null
    green: null
    blue: null
    entity_category: config
    icon: "mdi:palette"

light:
  - platform: neopixelbus
    type: RGB
    pin: GPIO3
    variant: WS2811
    num_leds: 150
    name: "Christmas Tree LEDs"
    gamma_correct: 1
    effects:
      addressable_lambda:
        name: "Solid 4-Color"
        update_interval: 60000ms
        lambda: |-
          esphome::light::LightState* c;
          float r, g, b;
          for (int i = it.size() - 1; i > 0; i--) {
              if (i % 4 == 0) {
                c = id(effect_color_1);
              } else if (i % 4 == 1) {
                c = id(effect_color_2);
              } else if (i % 4 == 2) {
                c = id(effect_color_3);
              } else {
                c = id(effect_color_4);
              }
              c->current_values_as_rgb(&r, &g, &b);
              it[i] = Color(r, g, b);
          }

  - <<: *effect_light
    name: "Christmas Tree Effect Color 1"
    id: effect_color_1
  - <<: *effect_light
    name: "Christmas Tree Effect Color 2"
    id: effect_color_2
  - <<: *effect_light
    name: "Christmas Tree Effect Color 3"
    id: effect_color_3
  - <<: *effect_light
    name: "Christmas Tree Effect Color 4"
    id: effect_color_4