# Basic Config
esphome:
  name: office-heater
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_sk

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

api:

ota:

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    id: button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status"

sensor:
  - platform: wifi_signal
    name: "Office Heater Wifi Signal"
    update_interval: 15s
  - platform: cse7766
    current:
      name: "Office Heater Current"
      accuracy_decimals: 1
    voltage:
      name: "Office Heater Voltage"
      accuracy_decimals: 1
    power:
      name: "Office Heater Power"
      accuracy_decimals: 1
      id: power
      on_value_range:
        above: 1600
        then: 
          - switch.turn_off: relay
          - homeassistant.event: 
              event: esphome.breaker_tripped
    update_interval: 5s
  - platform: integration
    name: "Office Heater Energy"
    sensor: power
    time_unit: h
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001

time:
  - platform: sntp
    id: the_time

switch:
  - platform: gpio
    name: "Office Heater"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin: GPIO13