esphome:
  name: laundry-drain-control-v2
  on_boot:
    priority: 600
    then:
      - if:
            condition:
              binary_sensor.is_off: water_sensor
            then:
              - switch.turn_on: drain

esp8266:
  board: d1_mini_lite

logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_sk

switch:
  - platform: gpio
    restore_mode: ALWAYS_OFF
    pin: 
      number: D4
      mode: OUTPUT_OPEN_DRAIN
      inverted: true
    name: "Drain Relay"
    id: drain

binary_sensor:
  - platform: gpio
    name: "Drain backed up"
    id: water_sensor
    pin:
      number: D0
      mode: INPUT_PULLDOWN
    filters:
      - delayed_on: 100ms
      - delayed_off: 250ms
    on_press:
      then:
        - switch.turn_off: drain
    

  - platform: template
    name: "Drain should stop"
    lambda: |-
      return id(water_sensor).state;
    filters:
      - delayed_off: 150s
    internal: true
    on_release:
      then:
        - if: 
            condition:
              binary_sensor.is_off: water_sensor
            then:
              - switch.turn_on: drain
    

