esphome:
  name: laundry-drain-control-v2
  on_boot:
    priority: 600
    then:
      - if:
          condition:
            binary_sensor.is_off: water_sensor
          then:
            - switch.turn_on: drain

globals:
  - id: relay_turned_off_at
    type: int
    restore_value: no
    initial_value: "0"
  - id: relay_turned_on_at
    type: int
    restore_value: no
    initial_value: "0"

esp8266:
  board: d1_mini_lite

logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_sk

time:
  - platform: homeassistant
    id: homeassistant_time

switch:
  - platform: gpio
    restore_mode: ALWAYS_OFF
    pin: 
      number: D4
      mode: OUTPUT_OPEN_DRAIN
      inverted: true
    name: "Drain Relay"
    id: drain
    on_turn_on:
      then:
        lambda: |-
          id(relay_turned_on_at) = id(homeassistant_time).utcnow().timestamp;
    on_turn_off:
      then:
        lambda: |-
          int water_detected_at = id(homeassistant_time).utcnow().timestamp;
          int time_off = id(relay_turned_on_at) - id(relay_turned_off_at);
          int time_on = water_detected_at - id(relay_turned_on_at);
          if (id(water_sensor).state && id(relay_turned_off_at) > 0 && id(relay_turned_on_at) > 0 && time_on < 1600) {
            id(cycle_off_time).publish_state(time_off);
            id(cycle_on_time).publish_state(time_on);
          }
          id(relay_turned_off_at) = id(homeassistant_time).utcnow().timestamp;

binary_sensor:
  - platform: gpio
    name: "Drain backed up"
    id: water_sensor
    pin:
      number: D0
      mode: INPUT_PULLDOWN
    filters:
      - delayed_on: 250ms
      - delayed_off: 5s
    on_press:
      then:
        - switch.turn_off: drain
    

  - platform: template
    name: "Drain should stop"
    lambda: |-
      return id(water_sensor).state;
    filters:
      - delayed_off: 600s
    internal: true
    on_release:
      then:
        - if: 
            condition:
              binary_sensor.is_off: water_sensor
            then:
              - switch.turn_on: drain
    
sensor:
  - platform: template
    name: "Last cycle off time"
    id: cycle_off_time
    unit_of_measurement: s
  - platform: template
    name: "Last cycle on time"
    id: cycle_on_time
    unit_of_measurement: s
