esphome:
    name: laundry-drain-control-v2
    platform: esp8266
    board: d1_mini_lite
    on_boot:
    priority: 600
    then:
      - if:
            condition:
              binary_sensor.is_off: drain_backup
            then:
              - switch.turn_on: drain

logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_sk

switch:
  - platform: gpio
    restore_mode: ALWAYS_OFF
    pin: 
      number: D4
      mode: OUTPUT_OPEN_DRAIN
      inverted: true
    name: "Drain Relay"
    id: drain
