esphome:
  name: "media-tag-scanner"

esp8266:
  board: d1_mini_lite

logger:

api:
  password: ""

ota:
  password: ""
  
wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_sk

i2c:
  scan: true

rc522_i2c:

